apiVersion: apps/v1
kind: Deployment
metadata:
  name: improved-restaurant-search
  labels:
    app: improved-restaurant-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: improved-restaurant-search
  template:
    metadata:
      labels:
        app: improved-restaurant-search
    spec:
      containers:
        - name: improved-restaurant-search
          image: "username/improved-restaurant-search:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
