apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplified-order-process
  labels:
    app: simplified-order-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplified-order-process
  template:
    metadata:
      labels:
        app: simplified-order-process
    spec:
      containers:
        - name: simplified-order-process
          image: "username/simplified-order-process:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
