apiVersion: v1
kind: Service
metadata:
  name: simplified-order-process
  labels:
    app: simplified-order-process
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: simplified-order-process